name: Backend Run Checks

env:
  FOLDER: server

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      folder: ${{ steps.filter.outputs.folder }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            folder:
              - '${{ env.FOLDER }}/**'

  linters:
    needs: check-file-changes
    if: ${{ needs.check-file-changes.outputs.folder == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: cd ./${{ env.FOLDER }} && yarn install --frozen-lockfile

      - name: Lint
        run: cd ./${{ env.FOLDER }} && yarn lint

      - name: Prettier Check
        run: cd ./${{ env.FOLDER }} && yarn prettier

      - name: TS Check
        run: cd ./${{ env.FOLDER }} && npm run tsc
